##creation of ONLINE_STORE_RAW db and schema 

CREATE OR REPLACE DATABASE ONLINE_STORE_RAW
CREATE OR REPLACE SCHEMA ONLINE_STORE_RAW


## Creation of tables of Online_Store_RAW:

create or replace TABLE ONLINE_STORE_RAW.ONLINE_STORE_RAW.CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_NAME VARCHAR(100),
	ZIP_CODE VARCHAR(100),
	primary key (CUSTOMER_ID)
);

create or replace TABLE ONLINE_STORE_RAW.ONLINE_STORE_RAW.CUSTOMER_ORDER (
	ORDER_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	ORDER_DATE VARCHAR(16777216),
	primary key (ORDER_ID)
);

create or replace TABLE ONLINE_STORE_RAW.ONLINE_STORE_RAW.ORDER_DETAILS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	PRODUCT_ID NUMBER(38,0),
	UNIT_PRICE NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	DISCOUNT NUMBER(38,0),
	TOTAL_PRICE NUMBER(38,0),
	primary key (ORDER_ID),
	foreign key (PRODUCT_ID) references ONLINE_STORE_RAW.ONLINE_STORE_RAW.PRODUCTS(PRODUCT_ID)
);

create or replace TABLE ONLINE_STORE_RAW.ONLINE_STORE_RAW.PRODUCTS (
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	PRODUCT_NAME VARCHAR(50),
	CATEGORY_ID NUMBER(38,0),
	UNIT_PRICE NUMBER(38,0),
	primary key (PRODUCT_ID),
	foreign key (CATEGORY_ID) references ONLINE_STORE_RAW.ONLINE_STORE_RAW.PROD_CATEGORY(CATEGORY_ID)
);

create or replace TABLE ONLINE_STORE_RAW.ONLINE_STORE_RAW.PROD_CATEGORY (
	CATEGORY_ID NUMBER(38,0) NOT NULL,
	CATEGORY_NAME VARCHAR(50),
	CATEGORY_DESCRIPTION VARCHAR(300),
	primary key (CATEGORY_ID)
); 
